FROM ubuntu:focal-20200720
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
    apt-get -qq update && \
    apt-get -y install --fix-missing \
    apt-utils \
    build-essential \
    binutils \
    binfmt-support \
    readline-doc \
    micro \
    wget \
    git \
    python3.8 \
    python3.8-doc python3.8-tk python3.8-venv python3.8-dev python3.8-doc python3.8-distutils
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py
